plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

android {
    namespace "com.safetyoffice.firemanager"
    compileSdk 35

    defaultConfig {
        applicationId "com.safetyoffice.firemanager"
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName "1.6.0"
    }

    sourceSets {
        main {
            java {
                exclude "com/mohamed/**"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation platform("com.google.firebase:firebase-bom:33.7.0")
    implementation "com.google.firebase:firebase-auth"
    implementation "com.google.firebase:firebase-firestore"
    implementation "com.google.android.gms:play-services-auth:21.3.0"
}
